Update test-gitlab-include.yml

diff --git a/test-gitlab-include.yml b/test-gitlab-include.yml
--- a/test-gitlab-include.yml
+++ b/test-gitlab-include.yml
@@ -35,7 +35,7 @@
     bash <<'EOF'
       #!/bin/bash
       source config.env
-      API_PATH="https://cad-report.vercel.app/api/v1/builds/buildReport"
+      API_PATH="https://api-observability.browserstack.com/ext/v1/builds/buildReport"
       REPORT_STATUS_COMPLETED="COMPLETED"
       REPORT_STATUS_NOT_AVAILABLE="NOT_AVAILABLE"
       REPORT_STATUS_TEST_AVAILABLE="TEST_AVAILABLE"
@@ -60,10 +60,10 @@
         REPORT_TIMEOUT=130
       fi
       
-      # if [[ "$REPORT_TIMEOUT" -lt 20 || "$REPORT_TIMEOUT" -gt 600 ]]; then
-      #   echo "Error: REPORT_TIMEOUT must be between 20 and 600 seconds."
-      #   exit 1
-      # fi
+      if [[ "$REPORT_TIMEOUT" -lt 20 || "$REPORT_TIMEOUT" -gt 600 ]]; then
+        echo "Error: REPORT_TIMEOUT must be between 20 and 600 seconds."
+        exit 1
+      fi
       
       # Function to make API requests
       make_api_request() {
